-- ============================================================================
-- muteeb.in — Supabase schema
-- ----------------------------------------------------------------------------
-- Recreates the database the site expects. Run this in the Supabase SQL editor
-- (Dashboard → SQL Editor → New query) if you ever recreate the project.
--
-- The site talks to Supabase ONLY through the Vercel functions in api/, which
-- use the service-role key (bypasses RLS). RLS is therefore enabled with no
-- public policies — the anon key (used client-side only for auth) can't read
-- or write table data directly.
-- ============================================================================

-- ---------------------------------------------------------------- profile ----
create table if not exists public.profile (
  id                 bigint generated by default as identity primary key,
  full_name          text default 'Baba Muteeb',
  title              text,
  bio                text,
  status_badge       text,
  location           text,
  available_for_work boolean default true,
  accent_color       text,
  email              text default 'hello@muteeb.in',
  instagram_handle   text default '@mr_muteeb_',
  headline           text,
  logo_url           text default '/images/logo.png',
  sound_enabled      boolean default true,
  typewriter_roles   jsonb,  -- string[]
  now_focus          jsonb,  -- { title, desc }[]
  quick_facts        jsonb,  -- string[]
  admin_passcode     text,
  github_url         text,
  twitter_url        text,
  linkedin_url       text,
  created_at         timestamptz default now(),
  updated_at         timestamptz default now()
);

alter table public.profile enable row level security;

-- Seed the single profile row (the admin studio updates it in place).
insert into public.profile (full_name, title, location, typewriter_roles, now_focus, quick_facts)
values (
  'Baba Muteeb',
  'I make things for the internet because it feels like magic you can actually use.',
  'Srinagar, Kashmir',
  '["STUDENT & NIGHT CODER","MAKER OF INTERNET THINGS","CLEAN UI EXPERIMENTER","PROBLEM SOLVER","CURIOSITY DRIVEN BUILDER"]'::jsonb,
  '[{"title":"LEARNING","desc":"Getting deep into the tricky parts of JavaScript."},{"title":"BUILDING","desc":"Small digital tools that fix highly specific annoyances I have."},{"title":"READING","desc":"Mostly technical documentation and web design blogs."},{"title":"THINKING","desc":"About why certain websites feel instantly comfortable to use."}]'::jsonb,
  '["I run on tea, not coffee","Can''t write code in silence","Know 4 languages, master of none","Midnight is my most productive hour"]'::jsonb
)
on conflict do nothing;

-- --------------------------------------------------------------- projects ----
create table if not exists public.projects (
  id            bigint generated by default as identity primary key,
  title         text not null,
  slug          text,
  subtitle      text,
  description   text,
  category      text default 'PERSONAL',
  tags          jsonb,                -- string[]
  image_url     text,
  live_url      text,
  github_url    text,
  metrics       jsonb,                -- { [key]: string }
  featured      boolean default false,
  display_order int default 0,
  created_at    timestamptz default now()
);

alter table public.projects enable row level security;

-- ---------------------------------------------------------------- thoughts ----
create table if not exists public.thoughts (
  id            bigint generated by default as identity primary key,
  title         text not null,
  slug          text,
  summary       text,
  content       text,
  tags          jsonb,                -- string[]
  read_time     text default '3 MIN READ',
  likes_count   int default 0,
  published_at  timestamptz default now(),
  featured      boolean default false
);

alter table public.thoughts enable row level security;

-- ------------------------------------------------------------------ skills ----
create table if not exists public.skills (
  id            bigint generated by default as identity primary key,
  name          text not null,
  category      text default 'LANGUAGES & TOOLS',
  level         int default 85,
  icon          text,
  display_order int default 0
);

alter table public.skills enable row level security;

-- --------------------------------------------------------------- guestbook ----
create table if not exists public.guestbook (
  id           bigint generated by default as identity primary key,
  name         text not null,
  handle       text default '@guest',
  message      text not null,
  avatar_color text default 'cyan',
  badge        text default 'VISITOR',
  approved     boolean default false,   -- entries need admin approval
  created_at   timestamptz default now()
);

alter table public.guestbook enable row level security;

-- --------------------------------------------------------------- messages ----
create table if not exists public.messages (
  id           bigint generated by default as identity primary key,
  sender_name  text not null,
  sender_email text not null,
  subject      text,
  body         text,
  read_status  boolean default false,
  created_at   timestamptz default now()
);

alter table public.messages enable row level security;

-- ----------------------------------------------------------------- storage ----
-- Image uploads (api/upload.js) go to a public bucket named "images", with a
-- folder prefix per use: general/ logo/ projects/
-- Create it from Dashboard → Storage → New bucket, or run:

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

-- ============================================================================ 
-- After creating the project, set these Vercel env vars and redeploy:
--   NEXT_PUBLIC_SUPABASE_URL   = https://<project-ref>.supabase.co
--   SUPABASE_SERVICE_ROLE_KEY  = <service_role key>
--   VITE_SUPABASE_URL          = https://<project-ref>.supabase.co
--   VITE_SUPABASE_ANON_KEY     = <anon key>
--   ADMIN_PASSWORD             = <admin studio passcode>
-- ============================================================================
